baseURL = "https://lowentropy.me/"
languageCode = "zh-CN"
title = "LowEntropy"
theme = "LE-base16"

enableRobotsTXT = true

hasCJKLanguage = true

pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "UA-120056178-1"

footnotereturnlinkcontents = "↩"

enableEmoji = true

[permalinks]
blog = "/blog/:year:month:day-:title/"
flight-rules = "/flight-rules/:year:month:day-:title/"

[[menu.main]]
    name = "ARCHIVE"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "FR"
    url = "/flight-rules/"
    weight = 2
[[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 3


[params]
  AuthorName = "Ray Wong"
  GitHubUser = "jinxiapu"
  Subtitle = "Bring Order to Chaos."
  
  footer = "&copy; RayHY 2018 | [LowEntropy](/) | [Flight Rules](/flight-rules/)"

[params.comments.isso]
Host = "https://comments.lowentropy.me/"

[blackfriday]
  hrefTargetBlank = true