baseURL = "https://rayhy.com/"
languageCode = "zh-CN"
title = "RAY后院"
theme = "ivy"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 10
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-120056178-1"
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
blog = "/blog/:year:month:day-:title/"
flight-rules = "/flight-rules/:year:month:day-:title/"

[params]
  Favicon = "/favicon.jpg"
  AuthorName = "王不对"
  Description = "理可顿悟，事须渐修"

[params.CDN]
#enable = false
enable = true
# Host must end with `/`
Host = "https://lowentropy.jinxiapu.cn/img/"

[params.comments.isso]
Host = "https://c.jinxiapu.cn/"

[params.katex]
base = "https://cdn.jsdelivr.net/npm/katex@0.10.1/dist/"
CSSintegrity="sha384-dbVIfZGuN1Yq7/1Ocstc1lUEm+AT+/rCkibIcC/OmWo5f0EA48Vf8CytHzGrSwbQ"
JSIntegrity="sha384-2BKqo+exmr9su6dir+qCw08N2ZKRucY4PrGQPPWU1A7FtlCGjmEGFqXCv5nyM5Ij"
AutoRenderIntegrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"

[blackfriday]
  hrefTargetBlank = true


[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "手册"
    url = "/flight-rules/"
    weight = 3
[[menu.main]]
    name = "笔记"
    url = "/paper-notes/"
    weight = 5
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 8
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 9
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 10
[[menu.main]]
    name = "订阅"
    url = "/index.xml"