[build]
publish = "public"
command = "hugo"

[[redirects]]
from = "https://lowentropy.netlify.com/*"
to = "https://lowentropy.me/:splat"
status = 301
force = true

[[redirects]]
  from = "/go-isso/*"
  to = "https://go-isso.lowentropy.me/:splat"
  status = 200
  force = true