[build]
publish = "public"
command = "hugo --minify"

[[redirects]]
from = "https://rayhy.com/*"
to = "https://wrong.wang/:splat"
status = 301
force = true

[[redirects]]
  from = "/go-isso/*"
  to = "https://go-isso.rayhy.com/:splat"
  status = 200
  force = true